when:
  - branch: develop
    event: [ manual ]
  - event: tag

steps:
  - name: build
    image: "docker.io/library/eclipse-temurin:21-jdk-alpine"
    commands:
      - ./gradlew shadowJar
    when:
      event: [ manual, tag ]

  - name: release
    image: "docker.io/woodpeckerci/plugin-release:0.2.4"
    settings:
      api_key:
        from_secret: "Woodpecker-Release-Token"
      files: "build/libs/*.jar"
      base-url: "https://di9.ru/git"
    when:
      event: [ tag ]
