name: Build and Release

on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: "8.13"

      - name: Build with Gradle
        run: gradle shadowJar

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
